### ISSUE TITLE
Get Body from the post and put method

### ISSUE THREAD

**Issue by neiesc** [hibri/HttpMock#102]
Is it possible to get Body from the post or put method?

**Comment by hibri** [comment]
Hi @neiesc,
Can you give me a few more details on what you are trying to achieve?

**Comment by neiesc** [comment]
An example:
![image](https://user-images.githubusercontent.com/251643/58808244-0be96080-85f0-11e9-82f0-6d1576e4db3f.png)
I would like to get the value of AcceptedWarnings in Return, type:
```
var acceptedWarnings = 0;
var _stubTaskServerApiHttp = HttpMockRepository.At($"http://localhost:3000");
_stubTaskServerApiHttp.Stub(x => x.Post($"/task_server/tasks"))
    .Return(() =>
    {
        acceptedWarnings = GetAcceptedWarnings();
        return @"
            {
                'status_code': 0,
                'message': 'Taks manager mocked by HttpMock, url /task_server/tasks',
                'task_id': '10'
            }";
    })
    .OK();
```

**Comment by neiesc** [comment]
Cool, thanks!
> Could you not construct the response body earlier?
I think, so

**Comment by neiesc** [comment]
I tested it, `LastRequest` is getting the first request and not the last one. @hibri

**Comment by hibri** [comment]
That's not what is expected. Sounds like a bug. Can you create a new issue with the failing test please? 

Thanks

**Comment by neiesc** [comment]
> Can you create a new issue with the failing test please?

Of course.
