### ISSUE TITLE
We could use the AAA Pattern

### ISSUE THREAD

**Issue by neiesc** [hibri/HttpMock#104]
https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80

What do you think?

**Comment by hibri** [comment]
The tests are written in that pattern, even if they are not explicitly called out.  :)

**Comment by neiesc** [comment]
I saw, but what do you think of being called AAA?

**Comment by hibri** [comment]
I don't see the need to call it out via extra comments, as long as the test is structured in that way.

**Comment by neiesc** [comment]
alright.
