### ISSUE TITLE
Is this library supported for Xamarin.iOS?

### ISSUE THREAD

**Issue by lieuchew** [hibri/HttpMock#107]
I tried to use this on iOS app (written using Xamarin.Forms). But whenever the app trigger HTTP web service call, it will return HTTP code 404, Server Not Found. The same code work fine for the Android app though.

**Comment by hibri** [comment]
Hi @lieuchew,
This hasn't been tested with Xamarin.iOS. It's intended to run as part of a integration testing or acceptance testing suite and not as a library within applications. 
What are you using the library for?

**Comment by lieuchew** [comment]
Hi hibri,

I am using it to mock the HTTP web service during the UI test. Was hoping it works on the iOS app too as it's working fine for our Android app (coded with Xamarin.Forms for both iOS and Android)

Seems like the iOS isn't working, as far as I have tested...

**Comment by hibri** [comment]
Could you reproduce the issue with a failing test?
