### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by oschwald** [hibri/HttpMock#31]
This library looks great, but the license does not appear to grant permission to use or copy the software. Would you consider putting this under a standard license such as MIT or [ISC](https://en.wikipedia.org/wiki/ISC_license)?

**Comment by hibri** [comment]
Hi Gregory,
Yes I will. That was the intention all along, never got around to it.

**Comment by oschwald** [comment]
Great. Thanks! :+1:

**Comment by oschwald** [comment]
Thanks again!
