### ISSUE TITLE
Expose PortHelper functionality

### ISSUE THREAD

**Issue by oschwald** [hibri/HttpMock#32]
It would be great to be able to run the server on a random open port to prevent possible collisions due to hard coding a particular port. I notice that you already have this functionality for your internal unit tests. It would be nice if it was exposed to users of the library in some way so that we don't have to duplicate that code ourselves.

**Comment by hibri** [comment]
@oschwald  Can you let me know what scenario you envisage using this with ?
The server and port are usually configured in the system under test in a config file, where the URL for the actual API would be, so it always has to be a known host and port.

**Comment by oschwald** [comment]
@hibri, my use case was testing a web service client API (that allows the setting of the host and port) on a CI machine that may have several builds running at once. That said, I ended up creating abstractions over `HttpClient` and `HttpWebRequest` and mocked those out rather than using a test server. This caused some code duplication and less coverage, but it simplified the testing setup.

**Comment by hibri** [comment]
PortHelper has been moved out of HttpMock, it's now the responsibility of the tests to manage ports of a stub. Feel free to use the code PortHelper code in the Integration test suite
