### ISSUE TITLE
Duplicate query parameters not supported

### ISSUE THREAD

**Issue by ykeysergit** [hibri/HttpMock#38]
When I use withParams(queryParams), the duplicate query parameter overrides the original query parameter. I would like to have something like ?date=123&date=678. Is there an elegant work-around?

**Comment by hibri** [comment]
Hi @ykeysergit,

Not at the moment. The query string is parsed into a Dictionary, https://github.com/hibri/HttpMock/blob/master/src/HttpMock/EndpointMatchingRule.cs#L51

Will think of something over the weekend. Happy to accept a PR too.

What is your test scenario ?

**Comment by ykeysergit** [comment]
Test scenario:
?date=gt2016-06-12&date=le2016-06-13

I was able to use url-constraint as a work-around, but addQueryParamter is much more elegant :) Thanks for looking into it!

**Comment by hibri** [comment]
@ykeysergit Thanks. I'll consider this for the next release.
