### ISSUE TITLE
AssertWasCalled.WithHeader not reusable after first request

### ISSUE THREAD

**Issue by ykeysergit** [hibri/HttpMock#44]
WithHeader only looks at the last request. Hence, AssertWithCall(x=>x.Post("/").WithHeader("a",...) and AssertWithCall(x=>x.Post("/").WithHeader("b",...) doesn't work.  The error says that the the second request did not have the expected header b.

Diving into the code, it seems that the RequestVerify looks for the first handler that matches the path.

**Comment by hibri** [comment]
This was by design. It looks at the last request for the handler. 
All the requests that are made to a handler are recorded, so it will be possible to to a search. Will have to make the search smarter. 

Thanks for suggesting this.
