### ISSUE TITLE
Creating/Disposing the same server

### ISSUE THREAD

**Issue by ykeysergit** [hibri/HttpMock#45]
I have a test suite which creates/disposes a server multiple times. Server.IsAvailable() returns true, but the HTTP request hangs until timeout. When I ran the tests individually, they pass.

**Comment by hibri** [comment]
Hi @ykeysergit,
Can you reproduce it  ? and send me the test suite ?

Thanks.

**Comment by ykeysergit** [comment]
Yes. Consistently. The test suite is like...

`public void Test1(){
var server = fixture.createServer() 
try{
...
}
finally{
server.Dispose();
}
}

public void Test1(){
var server = fixture.createServer() 
try{
...
}
finally{
server.Dispose();
}
}

`

Seems like there's a thread in the framework which is still running.

**Comment by hibri** [comment]
What is behind fixture.createServer ?

A correct usage example is here https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/HttpFactoryTests.cs
and here

https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/MultipleTestsUsingTheSameStubServerWithDifferentHttpMethods.cs#L8

I suggest sharing the mock server between tests, to avoid the cost of destroying and recreating the port that the server listens on. This can be an expensive operation. Dispose might not guarantee the port is released for use in time for the next test.

You can use .WithNewContext to clear the stubs that were setup in a previous tests. Create the server in a TestFixtureSetup (before all tests), and call .WithNewContext in a SetUp method before each test.

Hope this helps :)

**Comment by ykeysergit** [comment]
I did this so I can AssertWasCall with different expectations. Otherwise, the success of one test case may propogate to the next. I'll try WithNewContext.

**Comment by ykeysergit** [comment]
I think it may be due to something due to how I created the server. Stand by.

**Comment by ykeysergit** [comment]
Ok. The root cause is on my end. Thanks for your input!
