### ISSUE TITLE
HttpServer.Dispose unexpectedly disposes all http servers

### ISSUE THREAD

**Issue by ykeysergit** [hibri/HttpMock#47]
I noticed that calling dispose on one server, disposes the other servers. I verified with IsAvailable that the other servers were shutdown.

 public void Dispose()
        {
            if (_scheduler != null)
            {
                _scheduler.Stop();
                _scheduler.Dispose();
            }
            if (_disposableServer != null)
            {
                _disposableServer.Dispose();
            }
        }

_disposableServer = KayakServer.Factory
                            .CreateHttp(_requestProcessor, _scheduler)
                            .Listen(ipEndPoint);

Seems to be due to same IP?

**Comment by hibri** [comment]
There is only one server for each IP/Port combination.

**Comment by ykeysergit** [comment]
I have used different ports for each IHttpServer object. Does Kayak use port too?

**Comment by hibri** [comment]
Could you please send a test suite that reproduces the issue ?

**Comment by ykeysergit** [comment]
IHttpServer serverA=null, serverB=null, server=null;

try{
serverA = createA();
serverB = createB();
serverC= createC();
}
finally{
serverA.Dispose();
serverB.Dispose()
serverC.Dispose();
}

**Comment by hibri** [comment]
I'll need the full code :)  What is inside createA() ...

**Comment by ykeysergit** [comment]
I'm not allowed to release the code. I've written some tests around it. I've been able to narrow it down to FactoryGirl. Thanks for your input!
