### ISSUE TITLE
Regex issue

### ISSUE THREAD

**Issue by marceloinacio** [hibri/HttpMock#56]
Hi, I am using HttpMock in our UnitTests.
I had a problem with a large Url request. (404 Not Found)

On EndpointMatchingRule.cs #line 42 and for pathMatch.IsMatch(pathToMatch) is returning false
The interesting is if I send a request with more than 5K of "A" like "http://localhost:9191/AAAAAAAAA....
I have no problem.

I am attaching my example.
Thank you

Marcelo

[Program.txt](https://github.com/hibri/HttpMock/files/427767/Program.txt)

**Comment by hibri** [comment]
Hi Marcelo,
I'll take a look when I get back in two weeks. Have you looked at the limits of regexes in .Net ?

**Comment by marceloinacio** [comment]
Not yet. But it is working with a 32K object of "A" character.
Maybe some encoded character is broking the Regex
We can work together if you want.
Tell me when you get back.
Thanks


-------- Original message --------

**Comment by hibri** [comment]
Hi @marceloinacio 

Were you reproduce this with a failing test  ?
