### ISSUE TITLE
.NET 4.0 support

### ISSUE THREAD

**Issue by lukasz-lysik** [hibri/HttpMock#59]
It looks like NuGet is build for .NET 4.5 (even though the folder in which assembly is suggests that this is build for .NET 4.0: packages\HttpMock.1.3.0\lib\net40\HttpMock.dll). Any way that can be fixed?

**Comment by hibri** [comment]
Sure. Sorry didn't notice it. Can you send a PR if possible ?

**Comment by lukasz-lysik** [comment]
Hi. Could you review please? https://github.com/hibri/HttpMock/pull/60

**Comment by lukasz-lysik** [comment]
Hi @hibri. I've created another PR: https://github.com/hibri/HttpMock/pull/61
