### ISSUE TITLE
Assembly does not have a strong name.

### ISSUE THREAD

**Issue by netchkin** [hibri/HttpMock#63]
when I reference HttpMock nuget package from a signed assembly, the following error appears during build:
CS8002	Referenced assembly 'HttpMock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by hibri** [comment]
Hi @netchkin 
I won't be providing a signed assembly. If you need a signed assembly, feel free to compile from source. 
Can you tell me more about your use case ?

**Comment by netchkin** [comment]
Okay, thanks for the reply, my use case was that our corporate policy forces us to only use signed assemblies.
