### ISSUE TITLE
RequestHandler getBody() when multiple requests have been handled

### ISSUE THREAD

**Issue by dwpoulos** [hibri/HttpMock#64]
getBody() does a peek on the queue, so if we are testing multiple requests in a row getBody() will only return the first.  Example would be receiving an acknowledgement callback and then a result callback on the same url.
Would a getBody(int count) or List<string> getBodies()  or have getBody() do a dequeue make sense?
I haven't delved into it too much, so is there a way to define your own IRequestHandler, but I haven't gotten there yet.

**Comment by hibri** [comment]
Hi @dwpoulos,
getBodies() makes sense. It exposes the collection of recorded requests, for more operations, and won't be tied to the handler. 
The queue doesn't make sense anymore. It would help to have it as a searchable List of some type.
