### ISSUE TITLE
Some thread seems to be running after test ends

### ISSUE THREAD

**Issue by jesaremi** [hibri/HttpMock#66]
I created a very simple test as shown below, At the end of it I get this:

System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.

```

        [TestMethod]
        public void MockHttpServer()
        {
            var stubHttp = HttpMockRepository.At("http://localhost:8888");
            stubHttp.Stub(x => x.Post("/somepath")).Return("OK").OK();
        }
```

Is there a way to explicitly shutdown the server before exiting?
thanks

**Comment by hibri** [comment]
You can call dispose, or wrap it in a using block 
See https://github.com/hibri/HttpMock/blob/master/src/HttpMock/HttpServer.cs#L68

A better pattern is to reuse the stub, but call WithNewContext. I create the stub once per test fixture or in some cases once for the whole suite. 

https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/MultipleTestsUsingTheSameStubServerAndDifferentUris.cs#L25

What testing framework are you using?

**Comment by jesaremi** [comment]
I'm using VisualStudio Test.
Both methods produced the same error message:

       ```
 [TestMethod]
        public void MockHttpServer()
        {
            using (var stubHttp = HttpMockRepository.At("http://localhost:8888"))
            {
                stubHttp.Stub(x => x.Post("/metrics")).Return("OK").OK();
            }
        }
        [TestMethod]
        public void MockHttpServer2()
        {
            var stubHttp = HttpMockRepository.At("http://localhost:8888");
            stubHttp.Stub(x => x.Post("/metrics")).Return("OK").OK();
            stubHttp.Dispose();
        }
```

**Comment by hibri** [comment]
Thanks @jesaremi . I'll look into this over the weekend. I've only tested this with the NUnit TestRunner. First time I've had feedback from VS Test user. 
Happy to accept a PR if you find the issue in the meantime.
