### ISSUE TITLE
Kayak server not listening yet

### ISSUE THREAD

**Issue by marekstachura** [hibri/HttpMock#73]
Hey,

I'm getting the ```System.InvalidOperationException : Kayak server not listening yet.``` - any idea what could be the issue?
I'm using the example from the readme file, and it is working just fine on my Mac, however on Windows, it looks like the Kayak servers is not starting... Turned off the Windows Firewall - the same issue.

Thanks,
Marek

**Comment by hibri** [comment]
Hi Marek,
Could you try calling IsAvailable() right after you start the mock?
Which port are you trying to listen on and could you reproduce it in a test that I can run?
Which version of Windows are you on?

Thanks
Hibri

**Comment by marekstachura** [comment]
Hi @hibri.

please see https://bitbucket.org/mstachura/httpmocksample
But, it is working now just fine, not sure what was the issue... :(
I changed the target framework from 4.5.1 to 4.6.2 - upgraded the log4net and removed the generated `<startup>` element from the app.config...
Not sure which step helped here... I can try to replicate this if you want, if not, let's just close it.

Thanks,
Marek
