### ISSUE TITLE
Request to put an example of how to mock POST request which contains BODY

### ISSUE THREAD

**Issue by vinnakotars** [hibri/HttpMock#74]
Hi,

Request you to put an example on the main page of how to mock POST request which contains BODY.
If there are any restrictions on placing it there, please mail me ravi.sankar.vinnakota@outlook.com

Thanks,
Ravi.

**Comment by hibri** [comment]
Hi @vinnakotars 
There is an example here https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/HttpEndPointTests.cs#L44

**Comment by hibri** [comment]
This is not possible, and I don't think this is correct to implement. The POST body can be binary or text, it won't be feasible to match on this. 
What is the scenario you are testing? 
if the code path you are testing makes only one post request then just one mock should suffice.

**Comment by vinnakotars** [comment]
Hi Hibri,
I will try to do with the inputs you gave me. I will get back to you again after trying. The case I was referring was the post request is same, but body is different !
