### ISSUE TITLE
Assert.That(requestBody, Is.EqualTo(expected)); getting NullReference Exception in this line.

### ISSUE THREAD

**Issue by vasavisoma123** [hibri/HttpMock#77]
https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/HttpEndPointTests.cs#L44
in this example for post

**Comment by hibri** [comment]
Hi,
Can you give me more details on how you are running the tests?

**Comment by vasavisoma123** [comment]
created a console application and added all the package and running it.

**Comment by vasavisoma123** [comment]
I have taken UnitTestProject and executed the same line..Not getting any error.
Is this condtion only used in Unittestproject not in console application.could you pls clarify on this.

Thank you so much for the replies.

**Comment by hibri** [comment]
There are no test specific conditions. Can you post your code sample?
