### ISSUE TITLE
new WebClient().UploadString(("http://localhost:8080/api/v1/documents"), StudyId);

### ISSUE THREAD

**Issue by vasavisoma123** [hibri/HttpMock#79]
Bit urgent:

**Getting The remote server returned an error 404 not found..could any help in this pls.**
study Id is a string .
 

> new WebClient().UploadString(("http://localhost:8080/api/v1/documents"), StudyId);
>        new WebClient().UploadFile("http://localhost:8080/api/v1/documents", filename);
> 

the above 2 lines are giving problem.
string StudyId = "{TrialId : 223344}";
       string Result = "Object Id:    ,BaseObjectId";
       Dictionary<string, string> param = new Dictionary<string, string>()
       {
         {"admin", "lib"}

       };

       string filename = CreateFile();
        var r = StubHttp.Stub(x => x.Post(endpoint));
        r.WithParams(param);
        r.AddHeader("multipartform-data", "11");
              r.Return(Result).OK();
       new WebClient().UploadString(("http://localhost:8080/api/v1/documents"), StudyId);
       new WebClient().UploadFile("http://localhost:8080/api/v1/documents", filename);

**Comment by hibri** [comment]
What is your endpoint? 
Can you turn on logging?

**Comment by vasavisoma123** [comment]
api/v1/documents this is my endpoint

**Comment by hibri** [comment]
You've added .WithParams, but you don't pass in the params in your upload.
If you don't want the params to be considered i.e respond for all params, remove .WithParams

**Comment by vasavisoma123** [comment]
Accroding my scenario I want to send 2 params and one header and 2 body values..
params added in dictionary and as part of body one is file and another one is string library name

**Comment by hibri** [comment]
You are setting up the stub to be very specific by giving the params, so the stub responds only to the exact url + parameter combination.

**Comment by vasavisoma123** [comment]
how to specify the params in  new WebClient().UploadString(("http://localhost:8080/api/v1/documents"), StudyId);  ie.,(("http://localhost:8080/api/v1/documents/?what I need to specify to mection params..If I correctly understand..
is this is correct what I have understood.

**Comment by hibri** [comment]
https://msdn.microsoft.com/en-us/library/system.net.webclient(v=vs.110).aspx 
Those are query string params so you'll need to add them in the query string

**Comment by vasavisoma123** [comment]
Hi Hibri Thank you so much for your help...
 new WebClient().QueryString = myNameValueCollection;  I have  added this line of code to add my params..


Exectued code and passed testcase..

Could you confirm whether it  correct or not.

 IHttpServer StubHttp;
        StubHttp = HttpMockRepository.At("http://localhost:8080");
      string StudyId = "{124}";
       string Result = "Object Id:    ,BaseObjectId";
      
        string filename = CreateFile();

        NameValueCollection myNameValueCollection = new NameValueCollection();

        myNameValueCollection.Add("userid", "user1");
        myNameValueCollection.Add("lib", "C");

      // var r = StubHttp.Stub(x => x.Post(endpoint));
      var r = StubHttp.Stub(x => x.Post("/api/v1/documents"));
      //r.WithParams(param);
        r.AddHeader("multipartformdata", "11");
      r.Return(Result).OK();
      new WebClient().QueryString = myNameValueCollection; *******************************
      string s = new WebClient().UploadString("http://localhost:8080/api/v1/documents", StudyId);
       new WebClient().UploadFile("http://localhost:8080/api/v1/documents", filename);
        var requestBody = ((RequestHandler)r).LastRequest().Body;
        Assert.AreEqual(requestBody, StudyId);
