### ISSUE TITLE
How to use HTTP Mock for the url containing query string?

### ISSUE THREAD

**Issue by vinnakotars** [hibri/HttpMock#81]
Hi,

I am facing issue while mocking the the request url containing query strings. e.g., url is given below.
https://localhost:xxxxx/api/menu?someName=someValue&someId=someIdValue

Is there any specific way to implement that?
Thanks in advance.

Regards,
Ravi.

**Comment by vasavisoma123** [comment]
Hi Ravi,
try this ,it may help you
 NameValueCollection myNameValueCollection = new NameValueCollection();

        myNameValueCollection.Add("userid", "s")
        myNameValueCollection.Add("lib", "dPO");
new WebClient().QueryString = myNameValueCollection;

**Comment by vinnakotars** [comment]
Hi,

Got solution. We need to use either .WithParams(dictionaryObject) for the stub or .WithUrlConstraint(url => url.Contains("?") && url.Contains("key=value")) , etc.

Thanks,
Ravi.

**Comment by vinnakotars** [comment]
Hence closing.
