### ISSUE TITLE
.Net Framework support Issue

### ISSUE THREAD

**Issue by vkmasters** [hibri/HttpMock#82]
Hey,

I was trying to install HttpMock 2.1.0 on existing project that is targetted on .NETFramework,Version=v4.0,Profile=Client, I am getting below error:

> Could not install package 'HttpMock 2.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any solution or fix required in order to use this library with current targetted framework. 
Let me know, how could i achieve this. ?

**Comment by hibri** [comment]
Hi, It targets 4.5 and up so you'll have to upgrade your project to use it.
