### ISSUE TITLE
Ignore Headers when Matching

### ISSUE THREAD

**Issue by jonfinerty** [hibri/HttpMock#90]
Hi, I'm using this library to test my application and it works great, but it looks like in order to stub out an endpoint successfully I need to list all the headers that get sent in `WithHeaders`. Unfortunately our application sends out GUID correlation id's in the header so it's easy to predict their values. 

Is it (or would it be) possible to stub out an endpoint ignoring any given headers?

**Comment by jonfinerty** [comment]
I was just looking at doing a PR for this, but theres a question over intended behaviour when there's multiple stubs for the same endpoint with different headers. 

A possible solution is:

It should try and match with the stub with the most correct headers, falling back to stubs which match fewer and then finally fall back to a stub without any headers.

**Comment by hibri** [comment]
Hi @jonfinerty
The header match logic should return at the first match, does not need all headers.
https://github.com/hibri/HttpMock/blob/master/src/HttpMock/HeaderMatch.cs#L8
 
An approach would be to override the header matching logic to take a lambda, so you can inject your own custom logic. 
Something like https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/StubConstraintsTests.cs#L27

It could be 
```
.WithHeaders ( headers => headers.Contains(xxx))
```

**Comment by hibri** [comment]
If you have time could you send a PR with a failing test with this scenario?

**Comment by jonfinerty** [comment]
sure, I'll try to find some time this week

**Comment by jonfinerty** [comment]
Turns out we were adding a header with a null value, so I'm not sure what particularly was choking on that but we've fixed that bug in our application. Please close this issue if you want and if I find out something in HttpMock breaks on null headers I'll open a new issue/example test. Thanks and sorry for the mis-issue :)

**Comment by hibri** [comment]
Thanks @jonfinerty . No worries :)
