### ISSUE TITLE
Require proxy authentication

### ISSUE THREAD

**Issue by wilversings** [hibri/HttpMock#95]
I'm thinking that it might be useful for the mock to simulate a corporate infrastructure, in which an authentication to proxy is required.
So if the mock is set up to require proxy authenticaiton, the client should include the `Proxy-Authorization` header, otherwise will get 407.
Might such a feature be needed?

**Comment by hibri** [comment]
Thanks for suggesting this @wilversings , and it helps to understand the scenarios you are working with.

I'd like to keep HttpMock to help with mocking the behaviour of the API that the client is accessing. A proxy is **how** the clients accesses the API, and IMHO is a configuration concern. 

If a mock for the proxy authentication is needed for every API call, the tests become littered with a mock that doesn't provide any value to what's being tested. 

You can still test if the client sends the ```Proxy-Authorization``` header in a test of it's own, and use HttpMock to assert that the header is being sent.

**Comment by wilversings** [comment]
@hibri I understand, thanks for the reply!
