### ISSUE TITLE
HttpServer.IsAvailable slows down testing

### ISSUE THREAD

**Issue by stigc** [hibri/HttpMock#97]
If we create a new server and Disposes it after each test, HttpServer.IsAvailable() will pause for 5 seconds each time.

**Comment by hibri** [comment]
Hi @stigc 
I recommend not disposing the server after every test. The server listens on a socket, and this is an expensive resource, and closing a socket takes some time, and is not predictable. Hence the need to check if the socket is ready.

Don't dispose the server, but instead use .WithNewContext at the start of a test. This will clear out all existing handlers and stubs, but the server still keeps listening. You can dispose of the server with a test suite teardown. 

See https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/MultipleTestsUsingTheSameStubServerAndDifferentUris.cs#L25
